---
- name: Network Getting Started First Playbook

  gather_facts: no
  hosts: test-routers
  tasks:
  - name: show commands
    ios_command:
      commands:
        - terminal length 0
        - show version
        - show int description
    register: output1

  - debug:
      var: output1.stdout_lines

...

